### ISSUE TITLE
[Feature Request]: Bring back TLS support and Class name for ingress in Helm Chart

### ISSUE THREAD

**Issue by scali** [apache/hop#2053]
### What would you like to happen?

TLS support have been dropped for Ingress definition in the last PR related to ingress. It is a nice feature to bring back for server instance that needs HTTPS.
 
This feature could be activated optionnaly like this :

```yaml
// Some comments here
apiVersion: networking.k8s.io/v1
kind: Ingress
...
spec:
  ingressClassName: [ Ingress class name ]
  tls: [ TLS configuration ]
  rules:
    ...
```

### Issue Priority

Priority: 3

### Issue Component

Component: Containers
